---
- name: copy dependency_resolvers_conf.xml
  become: yes
  become_user: "{{ galaxy_user_name }}"
  copy: src=dependency_resolvers_conf.xml dest={{ galaxy_config_dir }}

- name: Install libtcl8.5 for Environment Modules
  become: yes
  become_user: root
  apt: name=libtcl8.5 state=present

#->seems like the job_conf.xml gets copies by the ansible-galaxy-sge-sanbi to the config file  

#- name: Create the syslink for the job_conf.xml
#  become: yes
#  become_user: "{{ galaxy_user_name }}"
#  file: >
#    src=/cip0/software/galaxy/shared_config/job_conf.xml
#    dest={{ galaxy_config_dir }}/job_conf.xml
#    state=link

- name: Create the syslink for the tool_destinations.yml
  become: yes
  become_user: "{{ galaxy_user_name }}"
  file: >
    src=/cip0/software/galaxy/shared_config/tool_destinations.yml
    dest={{ galaxy_config_dir }}/tool_destinations.yml
    state=link
